### ISSUE TITLE
BUG report: user defined offset does not work

### ISSUE THREAD

**Issue by fryzjergda** [Weeks-UNC/fpocketR#1]
HI I have found a bug in the offset setting.

Currently in the `__mian__.py` line 94 if the user wants to set up his own offset value it is overwritten with "None":
```python
    offset = util.get_offset(pdb, chain, offset) if offset is None else None
```

my fix for that:
```python
    offset = util.get_offset(pdb, chain, offset) if offset is None else offset
```

hope this helps!

Best,
Tomasz

**Comment by fryzjergda** [comment]
Also, you could mention in the documentation that if the user upload a pdb file with only "ATOM" records (so no HEADER, CMPND, DBREF), the user should specify his own offset value. Otherwise the prody.parsePDBHeader  will try to read these information, and as a result will not be able to (since they are not in the pdb file). I am talking about utils.get_offset()

**Comment by VonBoss** [comment]
Version 1.1.0 changes how offsets are calculated so that header information is no longer required.
