### ISSUE TITLE
“conda develop .” error

### ISSUE THREAD

**Issue by wsatbluesky** [Weeks-UNC/fpocketR#3]
When execute "conda develop ." , it shows error below:
```
(fpocketR) [zsu-root@mgt01 fpocketR]$conda develop .
usage: conda [-h] [-v] [--no-plugins] [-V] COMMAND ...
conda: error: argument COMMAND: invalid choice: 'develop' (choose from 'activate', 'deactivate', 'clean', 'compare', 'config', 'create', 'env', 'info', 'init', 'install', 'list', 'notices', 'package', 'remove', 'uninstall', 'rename', 'run', 'search', 'update', 'upgrade', 'content-trust', 'doctor', 'repoquery')
```
Is there something error?

**Comment by VonBoss** [comment]
It looks like anconda does not recognize that command. You may need to update your version of anaconda. What version are you using?

* Check anaconda version:

    conda --version

* update anconda:

    conda update conda

**Comment by wsatbluesky** [comment]
Sorry，because I use miniconda3，so I found it need an extra package：

conda install conda-build

After do that , "conda develop . "  works well.
